### ISSUE TITLE
Where does the "Full-IaaS" solution come into play

### ISSUE THREAD

**Issue by ghost** [GoTeamEpsilon/OpenEMR-AWS-Guide#13]
If you want costs to be as near-zero as possible for developing countries we will need to have a guide for deploying IaaS...perhaps all on the same instance. 

However maybe we should ignore that for now on AWS...Google Cloud is the best solution for "absolutely low as possible costs"...I've heard this repeatedly from developers in Eastern Europe and the Philipines...they have some instances that are "always free" and other good discounts.

Just want you to be aware that as of now I am starting with the mindset that our solution will be deployed with a US-based hospital who needs everything HIPAA requires and can probably spend at least $100 a month (maybe more).

**Comment by MatthewVita** [comment]
If you think about it, costs will incur with a traditional network as well (cables, power, switches, IT resources, etc). So roughly $100 bucks isn't much.

Do you think something like K8S will be good in this situation so it can be ran as a local cloud as well as on a cloud provider?

**Comment by MatthewVita** [comment]
Also, I agree we should "ignore this for now" for version 1 at least.

**Comment by ghost** [comment]
Ok "full-IaaS" should be possible with K8S and solve the "no-lock-in-and-run-on-prem-issue". So move this issue to Version 2.0.

Focus fully on AWS for version 1.0 and 1.5 for most likely US-based end customer.

**Comment by MatthewVita** [comment]
Was looking at Mesos today at lunch. Very interesting as well, but it comes with its own set of challenges. I hear that K8S is better because it has an opinionated scheduler.

**Comment by MatthewVita** [comment]
I learned the basics of K8S today (on a new project at work that uses it). It's a very awesome technology and while I think we'll definitely run into hurdles, I think it will do the trick for our version 2. Going to close this issue because I propose we run with K8S because it's

a) the big player in the industry (many success stories out there)
b) I have played around with the base features and now understand the concepts... no red flags from me :)
