### ISSUE TITLE
Secure Linux OS #1

### ISSUE THREAD

**Issue by ghost** [GoTeamEpsilon/OpenEMR-AWS-Guide#16]
So we'll be using the Amazon Linux AMI. Probably the most common one people use.
Look at the questions below. Eventually Jeffrey you'll find a way to secure/harden the instance, and then I guess 1). I can write a bash script for it / incorporate it in the CF template? Or 2). Maybe we'll make our own AMI?

Questions:
- Does this default AWS Linux AMI instance need to be hardened?
- If so how?
- Are you supposed to mess with the IPTables since I'm already creating security groups, ACLs, VPNs, etc?
- How does patching work? I think the instance just auto-updates? Does that change if we harden it?
- Should we use one of the hardened Linux images on the marketplace? I see some on there for 1 cent and 2 cent an hour.
- I know when I was reading the OpenEMR guide it had some good things (maybe they are really obvious to you though) to do. One of them was restricting access to the Apache Logs file. Another one was configuring of Apache.
- Should we even be using Apache? What about nginx?
- other stuff...

**Comment by MatthewVita** [comment]
> Does this default AWS Linux AMI instance need to be hardened?

Great question. To add my 2 cents. `/openemr/sites/default` should be fully encrypted to be HIPAA compliant. Can we use a Linux util to achieve this?

> Should we even be using Apache? What about nginx?

We must use Apache per OpenEMR. Nginx is not an option.

> How does patching work?

Do you mean patching the application? One can simply upload a new OpenEMR application zip file to ELB and it will deploy.

**Comment by Jeffrey-P-McAteer** [comment]
Finally found free time to investigate this, here are some initial ideas as well as sites/article sources:

[https://aws.amazon.com/articles/1233/](https://aws.amazon.com/articles/1233/)

By default AWS security groups block all & allow by exception. Because we're already using the AWS firewall we can ignore linux IPTables because we assume internal things are secure. If this changes (eg doctors can write code which runs in the cloud & has network access) we'll need to revisit IPTables.

We should disable SSH passwords & use keys only. The usual one-liner for that is
`sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config && /etc/init.d/sshd restart`

OS-level patching happens with `yum update`, and I assume we'll log output someplace in case anything needs extra TLC. It sounds like application-level patching is just a teardown & redeploy, and because we'll be doing load balancing we can just keep at least 1 openEMR instance running & wait until the new version is running to tear that one down.

Encrypting /openemr/sites/default is a breeze. The only drawback over traditional encryption is because we're deploying off an already-setup AMI it's going to be hairy to edit a partition table. Fortunately linux has a module to do filesystem-level encryption, [eCryptfs](https://wiki.archlinux.org/index.php/ECryptfs). I propose we use this to encrypt /openemr/sites/default, storing the encrypted directory someplace like /openemr/sites/encrypted_default & decrypting at boot-up. The real HIPAA question now is can we have the decryption key sitting on the same volume, or will we have to do network key-management (Machine A holds the decryption keys, which are requested by machines a,b,c...) ?

I think sticking to the default AMI and doing our own hardening will make things like audits easier, we can document the process instead of saying "It's a black box".

**Comment by ghost** [comment]
> Because we're already using the AWS firewall we can ignore linux IPTables because we assume internal things are secure.

1. Lol I have literally wondered this my whole life...I would always secure IPTables and not really be sure why I was doing that.

2. So it looks like OS patching is pretty easy. I was hoping AWS would even automate that (maybe they do if you use the super default Amazon Linux AMI??) but it looks like all we have to do is a cron job and pipe the output to a file where it is occasionally reviewed?

3. For encryption, AWS will rotate the keys for you and you can encrypt Elastic Block Store volumes just by checking the encryption box when you attach a volume. 
But then again maybe that's not possible because we are using Elastic Beanstalk which gives you less access at creation time (when things are normally encrypted) to your boxes...
Anyway you create the keys, which can be used for many different services, in IAM: 
![image](https://cloud.githubusercontent.com/assets/3357202/25463166/2936f354-2aa9-11e7-8999-62b73bca6c56.png)

**Comment by ghost** [comment]
Also @MatthewVita good to know about Apache. If anything I'm kind of glad, that constraint at least makes it easy to choose / move fast.

**Comment by ghost** [comment]
Also @Jeffrey-P-McAteer so it looks like when you create an AMI image you can select an option that encrypts the root volume...see [here](https://aws.amazon.com/blogs/aws/new-encrypted-ebs-boot-volumes/).

Also if you want to create a volume, encrypt it, and then (later) attach it to an image, here is an example of that:
![image](https://cloud.githubusercontent.com/assets/3357202/25463092/8e0dbed0-2aa8-11e7-896c-659cc162e0ec.png)

NOTE: not sure how all of this plays out with Elastic Beanstalk and then creating the AMI and then deploying to the AMI blah blah blah but I hope something in here was helpful: 
![image](https://cloud.githubusercontent.com/assets/3357202/25463344/8288186a-2aaa-11e7-80af-2cca16dc107d.png)

**Comment by Jeffrey-P-McAteer** [comment]
That's a lovely detail - the encryption is done outside the OS & just presented as a block device? Then we don't need to configure anything more than checking the box.

**Comment by MatthewVita** [comment]
> Finally found free time to investigate this, here are some initial ideas as well as sites/article sources:

Cool! Feel free to create your "sandbox working guide" here like @danielehrlich and I are doing: https://github.com/GoTeamEpsilon/OpenEMR-AWS-Guide/tree/master/Other

> we can ignore linux IPTables because we assume internal things are secure.

Yup.

> doctors can write code which runs in the cloud & has network access we'll need to revisit IPTables

I'm not sure it would matter. Basically, Elastic Beanstalk lets one zip up a PHP codebase and upload it. That's literally the deployment. Done. If something is changed that requires port changes, it's on the end user to figure that out.

> We should disable SSH passwords & use keys only

Not sure what exactly the default is for EC2 instance, but I had to use my `pem` file in order to SSH in (no password is required in this case).

> OS-level patching

Maybe I'm looking at this from a naive point of view, but if we're going with the base AWS AMI, can we just let Amazon deal with the patches and assume the best?

> Encrypting /openemr/sites/default is a breeze [...] eCryptfs

Sounds good to me, however, recall that this directory is mounted to the OS from EFS. We may need to look into what the best practices are here. Perhaps you can "flip a switch" on the EFS configuration and that's it. Not totally sure.

...

Great work, btw!

**Comment by ghost** [comment]
So the Amazon Linux AMI I just found out auto-updates...but I think we might lose that when we do a custom AMI for Elastic Beanstalk. Dunno. I'm going to address this in another issue. Look at the link below and read the first 4 questions. It talks about what I said above.

Regular AMI: https://aws.amazon.com/amazon-linux-ami/faqs/

Confusing Elastic Beanstalk document about custom platforms (do I have to use packer or can I just use an AMI I created??): http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/custom-platforms.html

**Comment by MatthewVita** [comment]
Q. Does Amazon EFS provide encryption of data at rest?

Amazon EFS does not currently provide the option to encrypt data at rest, but we will offer this option soon.

**Comment by MatthewVita** [comment]
:(

**Comment by ghost** [comment]
I'm going to close this out...it's too much of a management issue to do either something with Packer or to make a Custom AMI.

I think the Amazon regular AMI takes care of everything...see here: https://aws.amazon.com/amazon-linux-ami/
