### ISSUE TITLE
Test AWS Turnkey CouchDB image

### ISSUE THREAD

**Issue by MatthewVita** [GoTeamEpsilon/OpenEMR-AWS-Guide#5]
https://aws.amazon.com/marketplace/pp/B00AJZJVNS

We need to find a CouchDB solution that works/scales on AWS. Also needs to be HIPPA compliant and highly available.

**Comment by ghost** [comment]
Really wanted to suggest Mongo here because there is a stronger community and you can use it on RDS which makes security so much easier, but looks like Mongo on RDS isn't HIPPA certified :(

Probably for the best though because it's very easy to encrypt things with EC2...you just check a box and then the entire storage volume becomes encrypted and you can store the keys in a variety of different places.

**Comment by MatthewVita** [comment]
I see. It would also be kind of a pain to get Mongo to work in OpenEMR considering how tightly integrated Couch is at this point.

**Comment by MatthewVita** [comment]
Stupid question: how do you run a CouchDB cluster in AWS? ELB + ECS?

**Comment by MatthewVita** [comment]
note https://github.com/GoTeamEpsilon/OpenEMR-AWS-Guide/issues/14

**Comment by MatthewVita** [comment]
Not going the CouchDB route... see https://github.com/GoTeamEpsilon/OpenEMR-AWS-Guide/issues/14

Closing.
