### ISSUE TITLE
Solution Stack Name not valid for Elastic Beanstalk

### ISSUE THREAD

**Issue by vnktsh** [GoTeamEpsilon/OpenEMR-AWS-Guide#60]
Hi Team Epsilon,

To start with, thanks a lot for this tutorial and template to install OpenEMR in a breeze.
I followed the tutorial for N.Virginia on my AWS account(Free tier). However, in the mid of progress it got rolled back because of this issue:

15:54:00 UTC-0400 | CREATE_FAILED | AWS::ElasticBeanstalk::Environment | EBEnvironment | No Solution Stack named '64bit Amazon Linux 2017.03 v2.4.1 running PHP 7.0' found.

Once this event failed, the entire stack got rolled back.

**Comment by MatthewVita** [comment]
Interesting, it looks like the AMI may be wrong. Will look into this.

**Comment by jesdynf** [comment]
Hello, vnktsh. A few quick questions.
 * Can you verify that you're trying to use the stack in us-east-1?
 * Can you attach the full stack output?
 * Can you install the AWS CLI with your credentials and also attach the response from `aws elasticbeanstalk list-available-solution-stacks`?

**Comment by jesdynf** [comment]
Never mind all that, I think I spotted it. You got bit by http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/platform-history-php.html -- your account was newer than the cutoff date for the v2.4.1 solution, so you were only permitted access to the v2.4.2, a situation none of our testers would encounter. Restart from the new guide link and you should be good.

**Comment by vnktsh** [comment]
Hi Jesdynf, great that you have found the bug, however I wish I could test this. I realized in free tier I won't have free access to non t2.micro ec2 and db instances. 
Can I tinker with the template and modify it, so that it is safe for free tier users? (e.g. using micro instances and specifying a lesser storage capacities)?

**Comment by jesdynf** [comment]
Only to a limited extent -- you're certainly welcome to modify the stack, which you can find in `/assets/OpenEMR.json` and then submit to CloudFormation directly instead of using the encoded link from the guide, but I fear you may not be able to make the stack completely free. That said, our calculations are that the stack costs about $4.50/day, so call it $0.20/hr, and you can delete the stack at the conclusion of your experiment, so you could conduct a couple experiments for less than a dollar. 

Another alternative is to review the live [OpenEMR 5.0.0 demo](http://www.open-emr.org/wiki/index.php/Development_5.0.0_Demo).

Regardless of how you proceed, I recommend checking the section on billing alarms, which will help let you know if it looks like your monthly bill will be higher than you would prefer.

**Comment by MatthewVita** [comment]
Btw @vnktsh, we are certainly welcoming testers at this point. Let me know if you'd like me to Paypal you some funds for further testing.

**Comment by hellosanket** [comment]
Hi Matthew.. I am attempting to install OpenEMR AWS version and got the similar error: "No Solution Stack named '64bit Amazon Linux 2017.03 v2.4.1 running PHP 7.0' found." I went ahead by modifying the linux version from 2.4.1 to 2.4.3 based on the information given at "http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts.platforms.html#concepts.platforms.PHP". This time it processed the "AWS::ElasticBeanstalk::Environment" step, but now I am getting the error: CREATE_FAILED - Environment failed to launch. 
I am not sure how to proceed further. Please suggest.

**Comment by jesdynf** [comment]
The solution stack currently in the repo uses v2.4.2, not v2.4.1. How are
you launching your stack? Where is your template coming from?

I think if you use the current master guide from https://github.com/openemr/openemr/tree/master/cloud , you'll be able to install the batch successfully.

**Comment by hellosanket** [comment]
@jesdynf Thank you for your response. I tried to install from the current master guide, but got the following error: No Solution Stack named '64bit Amazon Linux 2017.03 v2.4.2 running PHP 7.0' found.". 

I think AWS is not supporting version 2.4.2 anymore, as mentioned at this link: "http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/platform-history-php.html". It looks like support was there till 8/10. Now the new supported version is 2.4.3 as per: "http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts.platforms.html#concepts.platforms.PHP"

**Comment by jesdynf** [comment]
Ugh, is this always going to be a thing? It is supported, but not for the newest of the new accounts.

That said, I want you to take /that/ OpenEMR.json file and modify it to use the 2.4.3 stack. It didn't work with the 2.4.1 you tried to modify because there have been Beanstalk changes since then, but now it might work.

**Comment by hellosanket** [comment]
hey it worked..thank you so much for your help..

**Comment by jesdynf** [comment]
Great to hear! Stop by the OpenEMR chat if you have any questions about the
machinery, I'll be delighted to help.

**Comment by MatthewVita** [comment]
👍
